### ISSUE TITLE
能否推出zap插件和Example Code

### ISSUE THREAD

**Issue by studyzy** [TencentCloud/tencentcloud-cls-sdk-go#1]
如题。对用使用zap的用户来说，怎么快速的实现将日志保存到CLS中？

**Comment by cupen** [comment]
可参考这个，目前只实现了阿里云 SLS，晚点支持腾讯云 CLS.
https://github.com/gamedev-embers/zap-setup

**Comment by cupen** [comment]
@studyzy  已支持腾讯云 CLS
https://github.com/gamedev-embers/zap-setup
