### ISSUE TITLE
是否能支持嵌套json数据写入

### ISSUE THREAD

**Issue by wu3396** [TencentCloud/tencentcloud-cls-sdk-go#3]
我的数据是有json嵌套数据类型，当使用sdk时发现这里不支持，只支持map[string]string的数据结构，是否能支持任意类型呢？
https://github.com/TencentCloud/tencentcloud-cls-sdk-go/blob/ab76c7617d871883060b9342468d1b901fb50ba2/utils.go#L12

**Comment by farmerx** [comment]
嵌套的话，需要对嵌套的 json 序列化一下
